// <auto-generated />
namespace Project2.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialize7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialize7));
        
        string IMigrationMetadata.Id
        {
            get { return "202012231456035_initialize7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
